#!/usr/bin/env bash
# DevOps failure mode: a credential rotated in one place and not the other.
#
# Overwrites PGPASSWORD in the app's <app>-db-credentials Secret with a value
# the database has never heard of, then rolls the Deployment so new pods pick
# it up. The process starts fine and stays Running -- /healthz is liveness
# only -- but /readyz runs a real SELECT 1, fails authentication, and the new
# pods never join the Service. This is the "Running but not Ready" trap with a
# change-management cause instead of an infrastructure one.
#
# The original password is saved to .chaos-backup/ (gitignored) because the
# patch destroys the only copy in the cluster; --undo restores it.
#
# Usage: rotate-secret.sh <app> [--undo]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BACKUP_DIR="${REPO_ROOT}/.chaos-backup"

APP="${1:?usage: rotate-secret.sh <app> [--undo]}"
MODE="${2:-break}"

NS="$APP"
SECRET="${APP}-db-credentials"
DEPLOY="${APP}-backend"
BACKUP="${BACKUP_DIR}/${APP}-db-credentials.pgpassword"
WRONG_PASSWORD="rotated-$(date +%s)-not-in-rds"

if [[ "$MODE" == "--undo" ]]; then
  if [[ ! -f "$BACKUP" ]]; then
    echo "No backup at ${BACKUP}." >&2
    echo "" >&2
    echo "Each app's database password is generated by scripts/setup.sh" >&2
    echo "(openssl rand) and stored only in this Secret -- there is no copy in" >&2
    echo "Terraform state to read it back from. Re-run setup.sh instead: it" >&2
    echo "generates a fresh password, ALTERs the role on RDS to match, and" >&2
    echo "re-applies the Secret." >&2
    echo "  ./scripts/setup.sh" >&2
    exit 1
  fi
  kubectl -n "$NS" patch secret "$SECRET" \
    -p "{\"stringData\":{\"PGPASSWORD\":\"$(cat "$BACKUP")\"}}"
  kubectl -n "$NS" rollout restart "deployment/$DEPLOY"
  rm -f "$BACKUP"
  echo ""
  echo "Password restored and ${DEPLOY} rolled. Confirm readiness comes back:"
  echo "  kubectl -n ${NS} get pods -w"
  exit 0
fi

mkdir -p "$BACKUP_DIR"
# Never overwrite an existing backup. Running a chaos script twice without
# an --undo in between would otherwise save the ALREADY-BROKEN values over
# the good ones, and --undo would then faithfully restore the fault.
# Here that guard is the difference between a recoverable lab and a re-run of
# setup.sh: the Secret holds the only copy of the password.
if [ -f "$BACKUP" ]; then
  echo "note: a rotation is already active here -- keeping the original backup"
else
  kubectl -n "$NS" get secret "$SECRET" -o jsonpath='{.data.PGPASSWORD}' \
    | base64 -d > "$BACKUP"
fi

echo "Rotating PGPASSWORD in ${SECRET} to a value RDS does not know..."
kubectl -n "$NS" patch secret "$SECRET" \
  -p "{\"stringData\":{\"PGPASSWORD\":\"${WRONG_PASSWORD}\"}}"
echo "Original password saved to ${BACKUP}"

echo ""
echo "Rolling ${DEPLOY} so new pods start with the rotated credential:"
kubectl -n "$NS" rollout restart "deployment/$DEPLOY"

cat <<EOF

The new pods will be Running but never Ready. Confirm the difference:
  kubectl -n ${NS} get pods
  kubectl -n ${NS} logs -l app=${DEPLOY} --tail=20 | grep -i password
  kubectl -n ${NS} get endpoints ${DEPLOY}

In Datadog, look at logs before you touch anything:
  service:${DEPLOY} status:error

Undo:
  ${BASH_SOURCE[0]} ${APP} --undo
EOF
